---
- name: Server Config LAMP
  hosts: "services"
  become: true
  become_user: root
  vars:
    - redis_bind: 127.0.0.1
  roles:

    - role: kbrebanov.selinux
      selinux_state: disabled

    - role: geerlingguy.repo-remi
    - role: geerlingguy.repo-epel

    - role: geerlingguy.firewall
    - role: DavidWittman.redis
    - role: MarioDevment.rabbitmq
    - role: MarioDevment.java8
    - role: MarioDevment.elasticsearch
    - role: MarioDevment.kibana
    - role: logstash
    
    - role: geerlingguy.ntp
      ntp_timezone: Europe/Madrid
    
  tasks:
    - name: Install latest version of "VIM" and "recommends"
      yum:
        name: vim
        state: latest

    - name: Install latest version of "curl" and "recommends"
      yum:
        name: curl
        state: latest

    - name: Start Service rabbitMQ
      command: "service rabbitmq-server start"

    - name: Install Plugins
      command: "rabbitmq-plugins enable rabbitmq_management"

    - name: Reset Service
      command: "service rabbitmq-server restart"